defaults:
  - evolution: reg_evolution

model:
  max_learn_length: 10
  max_predict_length: 10

dataset:
  ndatasets: 10
  nsamples: 100
  nfeatures: 2

pool:
  nscalars: 4
  nvectors: 4
  # TODO: add nmatrix

hydra:
  run:
    dir: ./outputs/${evolution.type}/type=circles/datasets=${dataset.ndatasets}_samples=${dataset.nsamples}_features=${dataset.nfeatures}_learn_len=${model.max_learn_length}_predict_len=${model.max_predict_length}_population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}

    # dir: ./outputs/circles/penalty/datasets=${dataset.ndatasets}/${evolution.type}/population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}
    # dir: ./outputs/moons/penalty/${evolution.type}/population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}

    # dir: ./outputs/circles_dataset/${evolution.type}/population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}